import type { Job } from '../types/job'

const now = Date.now()
const hoursAgo = (h: number) => new Date(now - h * 60 * 60 * 1000).toISOString()
const daysAgo = (d: number) => hoursAgo(d * 24)

export const SEED_JOBS: Job[] = [
  {
    id: 1,
    title: 'Senior Backend Engineer',
    company: 'Northwind Labs',
    companyLogoUrl: null,
    location: 'Bengaluru, India',
    remoteType: 'HYBRID',
    jobType: 'FULL_TIME',
    category: 'Engineering',
    salaryMin: 2200000,
    salaryMax: 3200000,
    currency: 'INR',
    description:
      'Own the design and scaling of our core services handling millions of daily requests. Work closely with product to ship features end to end.',
    requirements: '5+ years of backend experience, solid grasp of relational databases, experience with distributed systems.',
    applyUrl: null,
    applyEmail: 'careers@northwindlabs.example',
    status: 'OPEN',
    postedAt: daysAgo(1),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 2,
    title: 'Frontend Engineer (React)',
    company: 'Northwind Labs',
    companyLogoUrl: null,
    location: 'Remote',
    remoteType: 'REMOTE',
    jobType: 'FULL_TIME',
    category: 'Engineering',
    salaryMin: 1800000,
    salaryMax: 2600000,
    currency: 'INR',
    description:
      'Build delightful, accessible interfaces used by thousands of job seekers every day. You will own features from design handoff to production.',
    requirements: '3+ years with React, strong CSS fundamentals, an eye for detail and UX.',
    applyUrl: null,
    applyEmail: 'careers@northwindlabs.example',
    status: 'OPEN',
    postedAt: hoursAgo(2),
    updatedAt: null,
    closingDate: nextWeek(),
  },
  {
    id: 3,
    title: 'Product Designer',
    company: 'Fieldstone Studio',
    companyLogoUrl: null,
    location: 'Pune, India',
    remoteType: 'ON_SITE',
    jobType: 'FULL_TIME',
    category: 'Design',
    salaryMin: 1500000,
    salaryMax: 2100000,
    currency: 'INR',
    description:
      "Lead end-to-end product design for our consumer app, from research through polished, shippable UI.",
    requirements: 'A strong portfolio, comfort with Figma, experience partnering closely with engineers.',
    applyUrl: null,
    applyEmail: null,
    status: 'OPEN',
    postedAt: daysAgo(3),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 4,
    title: 'Data Analyst',
    company: 'Fieldstone Studio',
    companyLogoUrl: null,
    location: 'Hybrid - Pune',
    remoteType: 'HYBRID',
    jobType: 'FULL_TIME',
    category: 'Data',
    salaryMin: 1200000,
    salaryMax: 1800000,
    currency: 'INR',
    description:
      'Turn raw product and marketing data into decisions. Build dashboards and run experiments that shape the roadmap.',
    requirements: 'SQL fluency, experience with a BI tool, comfort presenting findings to non-technical stakeholders.',
    applyUrl: null,
    applyEmail: null,
    status: 'OPEN',
    postedAt: daysAgo(5),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 5,
    title: 'DevOps Engineer',
    company: 'Cascade Systems',
    companyLogoUrl: null,
    location: 'Remote',
    remoteType: 'REMOTE',
    jobType: 'CONTRACT',
    category: 'Engineering',
    salaryMin: 90000,
    salaryMax: 130000,
    currency: 'USD',
    description:
      'Harden our CI/CD pipelines and cloud infrastructure. You will own observability, deployments, and incident response tooling.',
    requirements: 'Experience with Docker, Kubernetes, GitHub Actions or similar, and infra-as-code.',
    applyUrl: 'https://example.com/careers/devops',
    applyEmail: null,
    status: 'OPEN',
    postedAt: hoursAgo(12),
    updatedAt: null,
    closingDate: nextWeek(),
  },
  {
    id: 6,
    title: 'Marketing Manager',
    company: 'Cascade Systems',
    companyLogoUrl: null,
    location: 'New York, USA',
    remoteType: 'ON_SITE',
    jobType: 'FULL_TIME',
    category: 'Marketing',
    salaryMin: 85000,
    salaryMax: 110000,
    currency: 'USD',
    description:
      'Own our brand voice and growth campaigns across channels, from content strategy to performance marketing.',
    requirements: '4+ years in B2B marketing, strong writing skills, comfort with analytics tools.',
    applyUrl: null,
    applyEmail: null,
    status: 'OPEN',
    postedAt: daysAgo(6),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 7,
    title: 'Customer Support Specialist',
    company: 'Harborline',
    companyLogoUrl: null,
    location: 'Remote',
    remoteType: 'REMOTE',
    jobType: 'PART_TIME',
    category: 'Customer Support',
    salaryMin: 35000,
    salaryMax: 48000,
    currency: 'USD',
    description: 'Be the friendly, sharp first line of support for our customers over chat and email.',
    requirements: 'Excellent written communication, patience, and a genuine desire to help people.',
    applyUrl: null,
    applyEmail: null,
    status: 'OPEN',
    postedAt: hoursAgo(9),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 8,
    title: 'Software Engineering Intern',
    company: 'Harborline',
    companyLogoUrl: null,
    location: 'Remote',
    remoteType: 'REMOTE',
    jobType: 'INTERNSHIP',
    category: 'Engineering',
    salaryMin: null,
    salaryMax: null,
    currency: 'USD',
    description:
      'A 3-month paid internship building real features alongside our engineering team, with dedicated mentorship.',
    requirements: 'Currently pursuing a CS degree or equivalent, familiarity with at least one modern language.',
    applyUrl: 'https://example.com/careers/internship',
    applyEmail: null,
    status: 'OPEN',
    postedAt: daysAgo(4),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 9,
    title: 'Sales Development Representative',
    company: 'Anchorpoint',
    companyLogoUrl: null,
    location: 'Chicago, USA',
    remoteType: 'ON_SITE',
    jobType: 'FULL_TIME',
    category: 'Sales',
    salaryMin: 55000,
    salaryMax: 75000,
    currency: 'USD',
    description: 'Generate and qualify pipeline for our enterprise sales team through outbound prospecting.',
    requirements: '1-2 years of SDR experience preferred, sharp communication skills, resilience.',
    applyUrl: null,
    applyEmail: null,
    status: 'OPEN',
    postedAt: daysAgo(8),
    updatedAt: null,
    closingDate: null,
  },
  {
    id: 10,
    title: 'Freelance Copywriter',
    company: 'Anchorpoint',
    companyLogoUrl: null,
    location: 'Remote',
    remoteType: 'REMOTE',
    jobType: 'FREELANCE',
    category: 'Marketing',
    salaryMin: null,
    salaryMax: null,
    currency: 'USD',
    description:
      'Write landing pages, email sequences, and ad copy for a fast-moving marketing team, project by project.',
    requirements: 'A portfolio of conversion-focused copy, fast turnaround, comfort with feedback.',
    applyUrl: null,
    applyEmail: null,
    status: 'CLOSED',
    postedAt: daysAgo(20),
    updatedAt: null,
    closingDate: null,
  },
]

function nextWeek(): string {
  return new Date(now + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
}
